version: '3'
services:

  zabbix-mysql:
    image: mysql:8.1.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD=${ENV_MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${ENV_MYSQL_ZBX_USER}
      - MYSQL_PASSWORD=${ENV_MYSQL_ZBX_PASSWORD}
      - MYSQL_DATABASE=zabbix
    networks:
      - zabbix-net

  zabbix-server:
    image: zabbix/zabbix-server-mysql:6.4-alpine-latest
    restart: always
    ports:
      - "10051:10051"
    volumes:
      - ./zabbix-server/zbx_env/usr/lib/zabbix/alerters:/usr/lib/zabbix/alerters:ro
      - ./zabbix-server/zbx_env/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
      - ./zabbix-server/zbx_env/var/lib/zabbix/export:/var/lib/zabbix/export:rw
      - ./zabbix-server/zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      - ./zabbix-server/zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      - ./zabbix-server/zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
      - ./zabbix-server/zbx_env/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
      - ./zabbix-server/zbx_env/var/lib/zabbix/snmptraps:/var/lib/zabbix/snmptraps:ro
      - ./log:/var/log/zabbix-server:rw
    environment:
      - ZBX_SERVER_HOST=zabbix-server
      - DB_SERVER_HOST=zabbix-mysql
      - DB_SERVER_PORT=3306
      - ZABBIX_LOGFILE=/var/log/zabbix-server/zabbix_server.log
      - MYSQL_ROOT_PASSWORD=${ENV_MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${ENV_MYSQL_ZBX_USER}
      - MYSQL_PASSWORD=${ENV_MYSQL_ZBX_PASSWORD}
      - MYSQL_DATABASE=zabbix
    depends_on:
      - zabbix-mysql
    networks:
      - zabbix-net

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:6.4-alpine-latest
    restart: always
    ports:
      - "19080:8080"
    volumes:
      - ./log:/var/log/zabbix-server:rw
    environment:
      - ZBX_SERVER_HOST=zabbix-server
      - DB_SERVER_HOST=zabbix-mysql
      - DB_SERVER_PORT=3306
      - ZABBIX_LOGFILE=/var/log/zabbix-server/nginx.log
      - MYSQL_ROOT_PASSWORD=${ENV_MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${ENV_MYSQL_ZBX_USER}
      - MYSQL_PASSWORD=${ENV_MYSQL_ZBX_PASSWORD}
      - MYSQL_DATABASE=zabbix
      - GRANT_PRIVS=ALL
      - PHP_TZ=Asia/Tokyo
    depends_on:
      - zabbix-mysql
      - zabbix-server
    networks:
      - zabbix-net

networks:
  zabbix-net:
    driver: bridge

